### ISSUE TITLE
Add animal types to previously submitted reports

### ISSUE THREAD

**Issue by mcary** [mcary/valley-fire-animals#17]
Someone should go down the list of reports submitted before we had an animal type field, determine that field from the summary/description, and update the report so we have it in the dedicated field.

Contact me for suggestions how to do this.

**Comment by ruralocity** [comment]
We got a message tonight from someone who's holding off on sharing the site with others until this is done—it looks like a bug in search when searching an animal type (dog, in this case) doesn't return what's expected. I chipped away at it tonight but need to go to bed—I'll wrap it up tomorrow.

**Comment by ruralocity** [comment]
I'm done with this. There are three with no photo and no specific mention of a type of animal, so they're still in the "none" category for now.
