### ISSUE TITLE
Add field for pet type/species

### ISSUE THREAD

**Issue by mcary** [mcary/valley-fire-animals#2]
Add a field so people can easily scan the type of animal.  Suggested types:

Cat
Dog
Horse
Barnyard
Pig
Rabbit
Small & Furry
Scales, Fins & Other
Wildlife

These align with a Lake County form.

The field should be called "animal_type", "category", or "species".  Since there is an "other" category, it should probably be required.  And the default should be empty.

This is a top feature request in community feedback.

**Comment by ruralocity** [comment]
I can put some time into this tonight. To clarify, is "other" a category alongside the species you listed here? Does there need to be a text input for more details on "other?"

**Comment by mcary** [comment]
Thanks!

I'd keep it simple; no text input for other.  You can look at the
current reports to see how many reports would have into that category if
you like.  These came from a general-purpose animal form on the web.

**Comment by calebhaye** [comment]
The Foster Homes PR contains an `Animal` model (with a simple `name` field).  It's necessary in order to populate the form which specifies they animals that people can foster, and their is a join model too, `AnimalFosterHome`.  Thoughts?

**Comment by calebhaye** [comment]
My thought is that this issue/request may no longer be necessary/appropriate.

**Comment by mcary** [comment]
Addressed by PR #8.

This issue is still a top feature request in community feedback, so it is still appropriate.  However, the question of whether to use a separate model vs. string field for Report#animal_type is definitely moot.  (We obviously needed the model.)
