### ISSUE TITLE
Add help text to "description"

### ISSUE THREAD

**Issue by mcary** [mcary/valley-fire-animals#3]
Add "help text" to the description field to suggest these attributes:
- Animal name
- Color
- Gender
- Breed
- Collar color and type
- Town lost or found in
- Distinctive markings

Some day these might become fields, but for now I'm not convinced that's necessary.

**Comment by racheljmakes** [comment]
I'll take this one.

**Comment by mcary** [comment]
Closed by PR #9.  Thanks, @rachelannejames!
